/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import conexion.conexionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import java.util.ArrayList;
import java.util.Arrays;



public class menuAlumno extends javax.swing.JFrame {
    
    public static String usuarioN;
    public static conexionDB conn = new conexionDB();
    public static ArrayList<String> listaP = new ArrayList<>();
    public String itemSelected;
                
    public menuAlumno() {
        
        initComponents();
        setLocationRelativeTo(null);
        usuarioN = login.u;
        nombreUsuario.setText(login.u);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
           
        cargarComidas();
        cargarBebidas();
        
         
               
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProductos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lbebidas = new javax.swing.JList<>();
        pedidos = new javax.swing.JButton();
        verOrden = new javax.swing.JButton();
        editInfo = new javax.swing.JButton();
        descripcion = new javax.swing.JLabel();
        agregarItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido(a): ");

        jLabel5.setText("Descripción:");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ListaProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaProductosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alimentos", jPanel1);

        Lbebidas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Lbebidas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                LbebidasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(Lbebidas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bebidas", jPanel2);

        pedidos.setText("Ver todos mis pedidos");
        pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosActionPerformed(evt);
            }
        });

        verOrden.setText("Ver mi orden");
        verOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verOrdenActionPerformed(evt);
            }
        });

        editInfo.setText("Editar mi información");
        editInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInfoActionPerformed(evt);
            }
        });

        descripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        descripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        agregarItem.setText("Agregar a mi orden");
        agregarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(editInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                        .addComponent(verOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(agregarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(agregarItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pedidos)
                        .addGap(12, 12, 12)
                        .addComponent(editInfo)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaProductosValueChanged
        // TODO add your handling code here:
        Lbebidas.clearSelection();
        itemSelected = ListaProductos.getSelectedValue();
        
            String consulta = "SELECT `Nombre`, `Descripcion`, `Tipo` FROM `recetas` WHERE `Tipo`=\"Alimento\""
                    + " AND `Nombre`=\""+itemSelected+"\"";
            Connection abrirConexion = conn.abrirConexion();
            try{
                PreparedStatement ps = abrirConexion.prepareStatement(consulta);
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    descripcion.setText("<html>"+ rs.getString("Descripcion")+ "</html>");
                }
            }catch(Exception e){
                System.out.println("We got an error " + e);
            }
             
            
            
            
       
    }//GEN-LAST:event_ListaProductosValueChanged

    private void LbebidasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_LbebidasValueChanged
        // TODO add your handling code here:
        ListaProductos.clearSelection();
        itemSelected = Lbebidas.getSelectedValue();
         
         
            String consulta = "SELECT `Nombre`, `Descripcion`, `Tipo` FROM `recetas` WHERE `Tipo`=\"Bebida\""
                    + " AND `Nombre`=\""+itemSelected+"\"";
            Connection abrirConexion = conn.abrirConexion();
            try{
                PreparedStatement ps = abrirConexion.prepareStatement(consulta);
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
           
                    descripcion.setText("<html>"+ rs.getString("Descripcion")+ "</html>");
                }
            }catch(Exception e){
                System.out.println("We got an error " + e);
            }
             
            
    }//GEN-LAST:event_LbebidasValueChanged

    private void pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosActionPerformed
         Pedidos p = new Pedidos();
         p.setVisible(true);
         p.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         
    }//GEN-LAST:event_pedidosActionPerformed

    private void editInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoActionPerformed
        // TODO add your handling code here:
        modificarInfoA modinfo = new modificarInfoA();
        modinfo.setVisible(true);
    }//GEN-LAST:event_editInfoActionPerformed

    private void verOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verOrdenActionPerformed
        
        verPedido verP = new verPedido();     
        verP.setVisible(true);
        
        verP.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_verOrdenActionPerformed

    private void agregarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarItemActionPerformed
        listaP.add(itemSelected);
        System.out.println(listaP);
        
    }//GEN-LAST:event_agregarItemActionPerformed
   
    
    private void cargarComidas(){
        
       String consulta = "SELECT `Nombre`, `Descripcion`, `Tipo` FROM `recetas` WHERE `Tipo`=\"Alimento\"";
       System.out.println(consulta);
       Connection abrirConexion = conn.abrirConexion();
       DefaultListModel lista1 = new DefaultListModel();
       
       try {
              
        PreparedStatement ps = abrirConexion.prepareStatement(consulta);
        ResultSet rs = ps.executeQuery();
            while(rs.next()) {
            
           String Nproducto = rs.getString("Nombre");
           lista1.addElement(Nproducto);    
            }
        ListaProductos.setModel(lista1);
           
       } catch(Exception ex){
           System.out.println("Este fue el error :" + ex);
       }
   
    }
    
    private void cargarBebidas(){
        
       String consulta = "SELECT `Nombre`, `Descripcion`, `Tipo` FROM `recetas` WHERE `Tipo`=\"Bebida\"";
       System.out.println(consulta);
       Connection abrirConexion = conn.abrirConexion();
       DefaultListModel listaBebidas = new DefaultListModel();
       
       try {
              
        PreparedStatement ps = abrirConexion.prepareStatement(consulta);
        ResultSet rs = ps.executeQuery();
            while(rs.next()) {
            
           String Nproducto = rs.getString("Nombre");
           listaBebidas.addElement(Nproducto);    
            }
        Lbebidas.setModel(listaBebidas);
           
       } catch(Exception ex){
           System.out.println("Este fue el error :" + ex);
       }
   
    }
    
            
    
    
    /**
     * @param args the command line arguments
     */
    

      
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new menuAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lbebidas;
    private javax.swing.JList<String> ListaProductos;
    private javax.swing.JButton agregarItem;
    private javax.swing.JLabel descripcion;
    private javax.swing.JButton editInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JButton pedidos;
    private javax.swing.JButton verOrden;
    // End of variables declaration//GEN-END:variables
}
