/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultListModel;
import static javax.swing.JOptionPane.showMessageDialog;
import static vistas.login.priv;
import static vistas.login.u;
import static vistas.vistaAdmin.vistaAdmin.conn;



public class Pedidos extends javax.swing.JFrame {

    DefaultListModel lmodel = new DefaultListModel();
    public String itemSeleccionado;
    DefaultListModel lmodel2 = new DefaultListModel();
    ArrayList<String> lp = new ArrayList<String>();
    
    public Pedidos() {
        initComponents();
        listar();
        setLocationRelativeTo(null);
    }

    public void listar(){
         
       String consulta = "SELECT * FROM `pedidos` WHERE `Estudiante`='"+menuAlumno.usuarioN+"'";
       HashSet<String> set=new HashSet();
       try {
                Connection abrirConexion = menuAlumno.conn.abrirConexion();
                PreparedStatement ps = abrirConexion.prepareStatement(consulta);
                ResultSet rs = ps.executeQuery();
                
                while(rs.next()){      
                    set.add(rs.getString("IDpedido"));
                }
            } catch (Exception e) {        
                System.out.println("Hay un error " + e);
                    }
       
       lmodel.addAll(set);
       listaPedido.setModel(lmodel);
       productos.setModel(lmodel2);
  
       
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPedido = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        HoraPedido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estadoP = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        productos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaPedido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPedido.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPedidoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaPedido);

        jLabel1.setText("Hora del pedido:");

        HoraPedido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HoraPedido.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setText("Numero de Pedido:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Estado:");

        estadoP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estadoP.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        estadoP.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        productos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(productos);

        jButton1.setText("Marcar como completado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HoraPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HoraPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(estadoP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaPedidoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPedidoValueChanged
        itemSeleccionado = listaPedido.getSelectedValue();
        lp.removeAll(lp);
        
        String consulta = "SELECT * FROM `pedidos` WHERE `Estudiante`='"+menuAlumno.usuarioN+"'"
                + " AND `IDpedido`='"+itemSeleccionado+"'";        
        
        try {
                 Connection abrirConexion = menuAlumno.conn.abrirConexion();
                 PreparedStatement ps = abrirConexion.prepareStatement(consulta);
                 ResultSet rs = ps.executeQuery();          
                 while(rs.next()){
                     HoraPedido.setText(rs.getString("Hora"));
                     estadoP.setText(rs.getString("Estado"));
                     lp.add(rs.getString("Producto") + " (" + rs.getString("Cantidad") + ")");
                     
                 }
             } catch (Exception e) {        
                 System.out.println("Hay un error " + e);
                     } 
        
        if(listaPedido.getValueIsAdjusting()) {
            lmodel2.removeAllElements();
            lmodel2.addAll(lp);
        }
        System.out.println(itemSeleccionado);
    }//GEN-LAST:event_listaPedidoValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String estado = "Entregado";
        String consulta = "UPDATE `pedidos` SET `Estado` = '"+estado+"' "
                + "WHERE `pedidos`.`IDpedido` = '"+itemSeleccionado+"'";
        String consulta1 = "DELETE FROM pedidos WHERE `pedidos`.`Estado` = 'Entregado'";
        try {
            Connection abrirConexion = conn.abrirConexion();
            PreparedStatement ps = abrirConexion.prepareStatement(consulta);
            ps.execute();
            PreparedStatement ps2 = abrirConexion.prepareStatement(consulta1);
            ps2.execute();
        } catch (Exception e) {
            System.out.println("Hay un error " + e);
   
        }
        lmodel.removeAllElements();
        listar();
        lmodel2.removeAllElements();
        HoraPedido.setText("");
        estadoP.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HoraPedido;
    private javax.swing.JLabel estadoP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaPedido;
    private javax.swing.JList<String> productos;
    // End of variables declaration//GEN-END:variables
}
