/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.vistaAdmin;

import conexion.conexionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import static javax.swing.JOptionPane.showMessageDialog;


public class agregarProducto extends javax.swing.JFrame {

    
    public static conexionDB con = new conexionDB();
     
    public agregarProducto() {
        initComponents();
        tipoP.removeAllItems();
        tipoP.addItem("Alimento");
        tipoP.addItem("Bebida");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        nombreP = new javax.swing.JTextField();
        tipoP = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionP = new javax.swing.JTextArea();
        agregar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        nombreP.setText("Nombre del Producto");
        nombreP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombrePFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombrePFocusLost(evt);
            }
        });

        tipoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPActionPerformed(evt);
            }
        });

        descripcionP.setColumns(20);
        descripcionP.setRows(5);
        descripcionP.setText("Agrega una descripcion del producto...");
        descripcionP.setWrapStyleWord(true);
        descripcionP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descripcionPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripcionPFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(descripcionP);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(cancelar)
                        .addGap(61, 61, 61)
                        .addComponent(agregar)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(cancelar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionPFocusGained
        descripcionP.setText("");
    }//GEN-LAST:event_descripcionPFocusGained

    private void nombrePFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombrePFocusGained
        nombreP.setText("");
    }//GEN-LAST:event_nombrePFocusGained

    private void nombrePFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombrePFocusLost
        
    }//GEN-LAST:event_nombrePFocusLost

    private void descripcionPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionPFocusLost
        
    }//GEN-LAST:event_descripcionPFocusLost

    private void tipoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String nombre = nombreP.getText();
        String tipo = tipoP.getItemAt(tipoP.getSelectedIndex());
        String descripcion = descripcionP.getText();
        System.out.println(nombre + tipo + descripcion);
        if(
                nombre.isEmpty()    ||
                tipo.isEmpty()   ||
                descripcion.isEmpty()  ||
                "Nombre del Producto".equals(nombre)  ||
                "Agrega una descripcion del producto...".equals(descripcion) 
               ) {showMessageDialog(null, "Por favor, llena todos los campos "
                       + "completamente ");
        }
        else {
           
            String consulta = "SELECT * from `recetas` WHERE Nombre='"+nombre+"'";
                
            try {
                Connection abrirConexion = con.abrirConexion();
                PreparedStatement ps = abrirConexion.prepareStatement(consulta); 
                ResultSet rs = ps.executeQuery();
                if(rs.next()) {
                    showMessageDialog(null, "Este nombre ya fue utilizado");
                    
                }else {
                    String agregandoDatos = "INSERT INTO `recetas` "
                            + "(Nombre, Descripcion, Tipo)"
                            + " VALUES ('"+nombre+"', '"+descripcion+"', '"+tipo+"')";
                    PreparedStatement ps2 = abrirConexion.prepareStatement(agregandoDatos);
                    ps2.execute();         
                    
                    showMessageDialog(null, "el producto se ha agregado correctamente");
                    System.out.println("el producto se ha agregado correctamente");
                    
                 
                    
                }
              
            } catch (Exception ex) {
                System.out.println("Hubo un error: " + ex);
            }
                
           
       }
        
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextArea descripcionP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField nombreP;
    private javax.swing.JComboBox<String> tipoP;
    // End of variables declaration//GEN-END:variables
}
