/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.vistaAdmin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import conexion.conexionDB;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.DefaultListModel;
import vistas.login;


public class vistaAdmin extends javax.swing.JFrame {

  
    
    String itemSeleccionado;
    DefaultListModel lmodel = new DefaultListModel();
    public static String usuarioActivo = login.u;
    public static conexionDB conn = new conexionDB();
    
    public vistaAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
        nombreA.setText(usuarioActivo);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    public void listar() {
        String consulta = "SELECT * FROM `pedidos` WHERE 1";
       HashSet<String> set=new HashSet();
       
       try {
                Connection abrirConexion = conn.abrirConexion();
                PreparedStatement ps = abrirConexion.prepareStatement(consulta);
                ResultSet rs = ps.executeQuery();
                
                while(rs.next()){      
                    set.add(rs.getString("IDpedido"));
                }
            } catch (Exception e) {        
                System.out.println("Hay un error " + e);
                    }
       
       lmodel.addAll(set);
       listaPedido.setModel(lmodel);
    }
    
    public void listar2(){
        itemSeleccionado = listaPedido.getSelectedValue();
        String consulta = "SELECT * FROM `pedidos` WHERE `IDpedido`='"+itemSeleccionado+"'";
        ArrayList<String> lp = new ArrayList<String>();

        try {
            Connection abrirConexion = conn.abrirConexion();
            PreparedStatement ps = abrirConexion.prepareStatement(consulta);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                estadoP.setText(rs.getString("Estado"));
                lp.add(rs.getString("Producto") + " (" + rs.getString("Cantidad") + ")\n");
                

            }
        } catch (Exception e) {
            System.out.println("Hay un error " + e);
        }

        if(listaPedido.getValueIsAdjusting()) {
            String listString = String.join("\n", lp);
            lproductos.setText(listString);
        }
        System.out.println(itemSeleccionado);
    }

    void cambiarEstado(String estado){
        String consulta = "UPDATE `pedidos` SET `Estado` = '"+estado+"' "
                + "WHERE `pedidos`.`IDpedido` = '"+itemSeleccionado+"'";
        try {
            Connection abrirConexion = conn.abrirConexion();
            PreparedStatement ps = abrirConexion.prepareStatement(consulta);
            ps.execute();
            listar2();
        } catch (Exception e) {
            System.out.println("Hay un error " + e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPedido = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        estadoP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreA = new javax.swing.JLabel();
        tomarP = new javax.swing.JButton();
        cancelarP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lproductos = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        cancelarP1 = new javax.swing.JButton();
        setPReady = new javax.swing.JButton();
        registrarA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Numero de Pedido:");

        listaPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listaPedido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPedido.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPedidoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaPedido);

        jLabel1.setText("Estado:");

        jLabel3.setText("Bienvenido(a):");

        tomarP.setText("Tomar Pedido");
        tomarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomarPActionPerformed(evt);
            }
        });

        cancelarP.setText("Cancelar pedido");
        cancelarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPActionPerformed(evt);
            }
        });

        lproductos.setEditable(false);
        lproductos.setColumns(20);
        lproductos.setRows(5);
        lproductos.setFocusable(false);
        jScrollPane2.setViewportView(lproductos);

        jButton1.setText("Ver menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cancelarP1.setText("Editar mi informacion");
        cancelarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarP1ActionPerformed(evt);
            }
        });

        setPReady.setText("Marcar pedido como listo");
        setPReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPReadyActionPerformed(evt);
            }
        });

        registrarA.setText("Agregar administrador");
        registrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarP, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarP1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setPReady, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tomarP, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registrarA, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreA, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(estadoP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tomarP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrarA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setPReady, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaPedidoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPedidoValueChanged
        listar2();
    }//GEN-LAST:event_listaPedidoValueChanged

    private void tomarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomarPActionPerformed
        
        cambiarEstado("Preparando");
    }//GEN-LAST:event_tomarPActionPerformed

    private void setPReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPReadyActionPerformed
        cambiarEstado("Listo");
    }//GEN-LAST:event_setPReadyActionPerformed

    private void cancelarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPActionPerformed
        cambiarEstado("Cancelado");
    }//GEN-LAST:event_cancelarPActionPerformed

    private void registrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAActionPerformed
        RegistrarA ra = new RegistrarA();
        ra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarAActionPerformed

    private void cancelarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarP1ActionPerformed
        
        modificarInfoAdmin madmin = new modificarInfoAdmin();
        madmin.setVisible(true);
        
    }//GEN-LAST:event_cancelarP1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu m = new menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarP;
    private javax.swing.JButton cancelarP1;
    private javax.swing.JLabel estadoP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPedido;
    private javax.swing.JTextArea lproductos;
    private javax.swing.JLabel nombreA;
    private javax.swing.JButton registrarA;
    private javax.swing.JButton setPReady;
    private javax.swing.JButton tomarP;
    // End of variables declaration//GEN-END:variables
}
